services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: gymtrack
      POSTGRES_PASSWORD: gymtrack123
      POSTGRES_DB: gymtrack
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
